version: '3.6'
services:
  cudos-contracts-front-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
