version: '3.6'
services:
  cudos-contracts-parser-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
